---
- name: install api-gateway
  hosts: all
  become: yes
  tasks:
    
    - name: install openjdk-8
      apt: 
        name: openjdk-8-jre
        update_cache: true
        state: present

    - name: install maven
      apt:
        name: maven
        state: present