---
- name: install api-gateway
  hosts: all
  become: yes
  tasks:
    - name: Move artifact.jar to ec2 instance
      copy: 
        src: artifact.jar
        dest: /home/ec2-user/artifact.jar

    - name: Execute java -jar
      shell: nohup java -Xmx256m -Xss32m -Djava.security.egd=file:/dev/./urandom -jar artifact.jar >> Log.log 2>&1 &



      