---
- name: install api-gateway
  hosts: all
  become: yes
  tasks:
    - name: Install openjdk-11-jdk
      apt:
        name: openjdk-11-jdk

    - name: Move artifact.jar to ec2 instance
      copy: 
        src: artifact.jar
        dest: /home/ubuntu/artifact.jar

    - name: Move artifact.jar to ec2 instance
      copy: 
        src: application.yml
        dest: /home/ubuntu/application.yml

    - name: Execute java -jar
      shell: nohup java -Xmx256m -Xss32m -Djava.security.egd=file:/dev/./urandom -jar artifact.jar >> Log.log 2>&1 &



      